apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: PersonalFinance
  annotations:
    github.com/project-slug: PatAKnight/PersonalFinance
    backstage.io/kubernetes-id: personalfinance
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: unknown
  owner: pataknight
